language: java

deploy:
  - provider: releases
    api_key: $GITHUB_OAUTH_TOKEN
    file: "./build/libs/gs-spring-boot-0.1.0.jar"
    skip_cleanup: true
    on:
      all_branches: true
  - provider: heroku
    api_key: $HEROKU_OAUTH_TOKEN
    app: snackshelf
    skip_cleanup: true
    on:
      all_branches: true
